# Generated by Django 5.2 on 2025-06-11 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('visibility', models.CharField(choices=[('show', 'Show'), ('hide', 'Hide')], default='show', max_length=10)),
            ],
        ),
    ]
