# Generated by Django 5.2 on 2025-06-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
