# Generated by Django 5.2 on 2025-06-11 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_rename_image_product_image4_product_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('about', models.TextField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('features', models.JSONField(blank=True, default=list, null=True)),
                ('visibility', models.CharField(choices=[('show', 'Show'), ('hide', 'Hide')], default='show', max_length=10)),
            ],
        ),
    ]
