# Generated by Django 5.2 on 2025-06-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='features',
        ),
        migrations.AddField(
            model_name='services',
            name='features_raw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
