# Generated by Django 5.2 on 2025-06-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0006_remove_services_features_services_features_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
