# Generated by Django 5.2 on 2025-06-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0007_alter_services_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImgSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('decription', models.CharField(max_length=100)),
                ('Btnlink', models.TextField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='HomePageImgSlider/')),
            ],
        ),
    ]
