# Generated by Django 5.2 on 2025-06-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0008_homepageimgslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageimgslider',
            name='Btnlink',
            field=models.CharField(max_length=100),
        ),
    ]
