# Generated by Django 5.2 on 2025-06-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0009_alter_homepageimgslider_btnlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageimgslider',
            name='BtnText',
            field=models.CharField(default='', max_length=100),
        ),
    ]
