# Generated by Django 5.2 on 2025-06-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0010_homepageimgslider_btntext'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advisory/')),
            ],
        ),
    ]
