# Generated by Django 5.2 on 2025-06-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0011_advisorycommitteemember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorycommitteemember',
            name='about',
        ),
    ]
