# Generated by Django 5.2 on 2025-06-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0012_remove_advisorycommitteemember_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='services',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
