# Generated by Django 5.2 on 2025-06-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0013_alter_services_options_services_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisorycommitteemember',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='homepageimgslider',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='advisorycommitteemember',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homepageimgslider',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
