# Generated by Django 5.2 on 2025-06-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0014_alter_advisorycommitteemember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisorycommitteemember',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='homepageimgslider',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='advisorycommitteemember',
            name='order',
        ),
        migrations.RemoveField(
            model_name='homepageimgslider',
            name='order',
        ),
        migrations.RemoveField(
            model_name='person',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.RemoveField(
            model_name='services',
            name='order',
        ),
        migrations.AddField(
            model_name='advisorycommitteemember',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepageimgslider',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
