# Generated by Django 5.2 on 2025-06-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0024_usercartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercartitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='usercartitem',
            name='product',
            field=models.CharField(max_length=255),
        ),
    ]
