# Generated by Django 5.2 on 2025-06-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0025_remove_usercartitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='usercartitem',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercartitem',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
